---
title: "[Rust][Trait]6. Error and TryFrom and FromStr"
tags: 
categories: 
- "Rust"
- "Trait"
---

原blog: https://github.com/pretzelhammer/rust-blog/blob/master/posts/tour-of-rusts-standard-library-traits.md
### Error
#### Error trait
``` Rust
trait Error: Debug + Display {
    // provided default impls
    fn source(&self) -> Option<&(dyn Error + 'static)>;
    fn backtrace(&self) -> Option<&Backtrace>; // unstable
    fn description(&self) -> &str; // rustc_deprecated since = "1.42.0"
    fn cause(&self) -> Option<&dyn Error>; // rustc_deprecated since = "1.33.0"
}
```
* `fn source(&self) -> Option<&(dyn Error + 'static)>;`
    * 默认实现是空的`None`，有需要的话可以覆写加上自己的实现
    * `source`的意思是`The lower-level source of this error, if any.`
* `fn backtrace(&self) -> Option<&Backtrace>;`
``` Rust
/// Returns a stack backtrace, if available, of where this error occurred.
///
/// This function allows inspecting the location, in code, of where an error
/// happened. The returned `Backtrace` contains information about the stack
/// trace of the OS thread of execution of where the error originated from.
///
/// Note that not all errors contain a `Backtrace`. Also note that a
/// `Backtrace` may actually be empty. For more information consult the
/// `Backtrace` type itself.
#[unstable(feature = "backtrace", issue = "53487")]
fn backtrace(&self) -> Option<&Backtrace> {
    None
}
```
* `fn description(&self) -> &str;`、`fn cause(&self) -> Option<&dyn Error>;`两个废弃接口，分别被`Display trait`和`fn source`取代了


### TryFrom
#### TryFrom trait
``` Rust
trait TryFrom<T> {
    type Error;
    fn try_from(value: T) -> Result<Self, Self::Error>;
}

trait TryInto<T> {
    type Error;
    fn try_into(self) -> Result<T, Self::Error>;
}

// same as `From` and `Into`
// impl TryFrom<T> and TryInto<T> impl is automatically provided by generic blanket impl below.
impl<T, U> TryInto<U> for T
where
    U: TryFrom<T>,
{
    type Error = U::Error;

    fn try_into(self) -> Result<U, U::Error> {
        U::try_from(self)
    }
}
```

#### Playground Code
``` Rust
use std::convert::TryFrom;
use std::fmt;

#[derive(Debug)]
struct Point {
    x: i32,
    y: i32,
}

#[derive(Debug)]
struct OutOfBounds;

impl fmt::Display for OutOfBounds {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "out of bounds")
    }
}

impl TryFrom<(i32, i32)> for Point {
    type Error = OutOfBounds;
    fn try_from((x, y): (i32, i32)) -> Result<Self, Self::Error> {
        if x.abs() > 1000 || y.abs() > 1000 {
            return Err(OutOfBounds);
        }
        Ok(Point { x, y })
    }
}

#[test]
#[should_panic]
fn will_panic() {
    let _ = Point::try_from((11111, 11111)).expect("");
}

fn main() {
    let pp = Point::try_from((100, 100)).unwrap();
    println!("{:?} : {},{}", pp, pp.x, pp.y);
}
```

### FromStr
#### FromStr trait
``` Rust
trait FromStr {
    type Err;
    fn from_str(s: &str) -> Result<Self, Self::Err>;
}
```
* `trait From`的限定加强版，可能失败的转换
* `trait TryFrom`的str限定版本，等同于`TryFrom<&str>`
``` Rust
// suppose we have impl FromStr for TypeA here.
impl FromStr for TypeA {
    type Err = SomeError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        //... with very complex code.
    }
}

// easy impl and we got `try_from() && try_into()` with &str for TypeA
impl TryFrom<&str> for TypeA {
    type Error = SomeError;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        <TypeA as FromStr>::from_str(s)
    }
}
```

#### Playground Code
``` Rust
use std::iter::Enumerate;
use std::num::ParseIntError;
use std::str::{Chars, FromStr};

#[derive(Debug)]
struct Point {
    x: i32,
    y: i32,
}

#[derive(Debug)]
struct ParsePointError;

impl From<ParseIntError> for ParsePointError {
    fn from(_: ParseIntError) -> Self {
        ParsePointError
    }
}

impl FromStr for Point {
    type Err = ParsePointError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let get_num =
            |char_indexs: &mut Enumerate<Chars<'_>>| -> Result<(usize, usize), ParsePointError> {
                let is_num = |(_, c): &(usize, char)| matches!(c, '0'..='9' | '-');
                let isnt_num = |t: &(usize, char)| !is_num(t);

                let (start, _) = char_indexs
                    .skip_while(isnt_num)
                    .next()
                    .ok_or(ParsePointError)?;
                let (end, _) = char_indexs
                    .skip_while(is_num)
                    .next()
                    .ok_or(ParsePointError)?;

                Ok((start, end))
            };

        let mut char_indexs = s.chars().enumerate();

        let (x_begin, x_end) = get_num(&mut char_indexs)?;
        let (y_begin, y_end) = get_num(&mut char_indexs)?;

        let x = s[x_begin..x_end].parse::<i32>()?; // need impl From<ParseIntError> for ParsePointError {}
        let y = s[y_begin..y_end].parse::<i32>()?;

        Ok(Point { x, y })
    }
}

fn main() {
    let p = "(1,2)".parse::<Point>();
    println!("{:?}", p);
}

```